trigger:
  branches:
    include:
      - develop
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Utiliser Node.js'

  - script: npm ci
    displayName: 'Installer les dépendances (racine)'

  - script: |
      cd logic-qcm-plus
      npm ci
      npm run build
    displayName: 'Build logic-qcm-plus'

  - script: |
      cd client-qcm-plus
      npm ci
      npm run lint
      npm run format:check
      npm run build
    displayName: 'Build client-qcm-plus'
