trigger: none # ANNOTATION: on désactive le déclenchement automatique direct
pr: none # ANNOTATION: pas déclenché par une PR

resources:
  pipelines:
    - pipeline: logicBuild
      source: MarysaR.logic-qcm-plus # ANNOTATION: nom exact du pipeline logic
      project: qcm-plus # ANNOTATION: projet DevOps
      trigger:
        branches:
          include:
            - develop
            - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.19.1'
    displayName: 'Utiliser Node.js 20.19.1'

  - checkout: self
    displayName: 'Checkout client-qcm-plus'

  - download: current
    artifact: logicPackage
    displayName: 'Télécharger artefact logic-qcm-plus'

  - script: |
      cd client-qcm-plus
      npm ci
      npm install $(Pipeline.Workspace)/logicPackage/logic-qcm-plus-*.tgz
    displayName: 'Installer dépendances + logic-qcm-plus'

  - script: |
      cd client-qcm-plus
      npm run lint
      npm run format:check
      npm run build
    displayName: 'Build client-qcm-plus'
